name: generate animation

on:
  # run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the main branch
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Step 1: generate the GitHub contribution snake
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      # Step 2: Checkout the output branch and create it if it doesn't exist
      - name: Checkout output branch
        uses: actions/checkout@v2
        with:
          ref: output
        continue-on-error: true  # continue even if the branch doesn't exist

      # Step 3: Create the output branch if it doesn't exist
      - name: Create output branch if it doesn't exist
        run: |
          git branch -M output || git checkout -b output
        continue-on-error: true

      # Step 4: Push the content to the output branch
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


